### ISSUE TITLE
code does not persist between interactions.

### ISSUE THREAD

**Issue by chuckdelcamp** [raffaeletani/ambiplayer#1]
Wonderful GUI and Functionality, thanks.

Using the GUI, I am able to "start" an item. Watching the console, I'm able to watch the GET request to start it.
![image](https://github.com/raffaeletani/ambiplayer/assets/11756610/f63b4060-4d3a-4675-8dc0-49c6af2cb542)
```
[GIN] 2024/06/22 - 18:17:43 | 200 |      93.029µs |       127.0.0.1 | GET      "/api/v1/start?code=f58585c59f6eeed4e4dfa9f5442ec9e9"
Playing sound: 01 - Key of A Pads.mp3
```

Using the GUI again, I can press STOP or FADE out for the individual item:
![image](https://github.com/raffaeletani/ambiplayer/assets/11756610/6c5fcbc9-f740-407e-8066-c3092c61ecb7)

The CODE remains consistent for the START calls (consistent with the code displayed in the GUI), however the STOP and FADEOUTSTOP calls use a different code each time.
![Screenshot from 2024-06-22 18-14-54](https://github.com/raffaeletani/ambiplayer/assets/11756610/d84580f6-b852-43e7-9cfd-b0c14f5544e5)

If I attempt to use the "consistent" code in to issue a stop call, the program crashes with a memory address error:
![image](https://github.com/raffaeletani/ambiplayer/assets/11756610/58eda2b5-57bd-4ec5-b034-0b36d3ccac92)

As a REST API user it would be great to be able to make a call to stop a specific media. I might be missing something in how the "code" is intended to be used.

**Comment by raffaeletani** [comment]
Each time you start a library item, the resulting active playback item gets created with a new code.
I did this because you can start an lib item multiple times and have them play simultaneously and still be able to control the active playbacks individually.

We could return the active playbacks code after a start call via api, or store the codes of a lib items active playback in the lib and lookup this list on a stop call to the lib item.

As i only use the fadeoutstopall via api, this remained unfinished

**Comment by raffaeletani** [comment]
calling the actions play, pause, stop, fadeoutstop with the library items code, applies them to all spawned instances (active playbacks) of that library item, whereas the stopall, playall, pauseall and fadeoutstopall still apply for all active playbacks

**Comment by chuckdelcamp** [comment]
Works like a charm. Thanks!
